---
title: "Cleaning Raw Data Experiment 2"
author: "Juan Carpio"
output: html_document
---


## Setting directory and relevant library
```{r, echo=TRUE, eval=TRUE, include=TRUE, cache=FALSE, warning=FALSE}

#Opening relevant library
library("dplyr")

## Change working directory
setwd("C:/Users/K56CA/Dropbox/PhD/Experiments Incentives/Follow_Up_Incentives/incentives-repo")

```


## Reading and cleaning data set
```{r,echo=TRUE, eval=TRUE, include=TRUE, cache=FALSE, warning=FALSE}

## read raw_data
dfraw<-read.csv("raw_data_Exp2.csv", na.strings=c("NA"), stringsAsFactors=FALSE)
data<- dfraw %>% filter(V10=="1")# select valid cases

# store and validate total number of participants
n<-length(data[,1])
n

## Name variables
variables<-c("gender", "age", "income","employment","B2vsA1",
             "D4vsC3","B2vsC3","D4vsE5","A1vsE5","A1vsD4","B2vsD4",
             "B2vsE5","C3vsA1","C3vsE5","F6vsG7","F6vsH8","G7vsH8")



#Separate Groups

### No-Reciprocity Group
g1<- data %>% select(Q79,Q75,Q73,Q77,B2vsA1,D4vsC3,B2vsC3,D4vsE5,
                     A1vsE5,A1vsD4,B2vsD4,B2vsE5,C3vsA1,C3vsE5,
                     F6vsG7,F6vsH8,G7vsH8) %>% 
        filter(B2vsA1!="")
colnames(g1)<-variables

### Reciprocity Group
g2<- data %>% select(Q79,Q75,Q73,Q77,B2vsA1.1,D4vsC3.1,B2vsC3.1,
                     D4vsE5.1,A1vsE5.1,A1vsD4.1,B2vsD4.1,B2vsE5.1,
                     C3vsA1.1,C3vsE5.1,F6vsG7.1,F6vsH8.1,G7vsH8.1)%>%
        filter(B2vsA1.1!="")
colnames(g2)<-variables

### No-Awareness Group
g3<- data %>% select(Q79,Q75,Q73,Q77,B2vsA1.2,D4vsC3.2,B2vsC3.2,
                     D4vsE5.2,A1vsE5.2,A1vsD4.2,B2vsD4.2,B2vsE5.2,
                     C3vsA1.2,C3vsE5.2,F6vsG7.2,F6vsH8.2,G7vsH8.2)%>%
            filter(B2vsA1.2!="")
colnames(g3)<-variables


#Building final data set
gr_data<- rbind(g1,g2,g3)
######gr_data[is.na(gr_data)] <- 0
tidy<-apply(gr_data, 2, as.numeric)

# Defining Length of each group
l1<- nrow(g1)
l2<- nrow(g2)
l3<- nrow(g3)

# Create vector defining each experimental condition
cond_length<-c(l1,l2,l3)
condition<- rep.int(c(1:3), times= cond_length)

# Joining data with groups information
clean<-cbind(tidy, condition)

# Create CSV File with clean data
write.csv(clean, file="clean_data_exp2.csv")

```

##Sample dataset
```{r, echo=TRUE}
head(clean)
```
