---
title: "Cleaning Raw Aata - Experiment 3"
author: "Juan Carpio"
output: html_document
---

## Setting directory and relevant library
```{r, echo=TRUE, eval=TRUE, include=TRUE, cache=FALSE, warning=FALSE}

#Opening relevant library
library("dplyr")

## Change working directory
setwd("C:/Users/K56CA/Dropbox/PhD/Experiments Incentives/Follow_Up_Incentives/incentives-repo")

```


## Reading and cleaning data set
```{r,echo=TRUE, eval=TRUE, include=TRUE, cache=FALSE, warning=FALSE}

## read raw_data
df<-read.csv("raw_data_Exp3.csv", na.strings=c("NA"), stringsAsFactors=FALSE)
data<- df %>% filter(Q51=="1")# select valid cases

# store and validate total number of participants
n<-length(data[,1])
n

## Name variables
variables<-c("gender", "age","income","employment","B2vsC3",
             "C3vsE5","A1vsE5","A1vsC3","A1vsD4","C3vs6F","A1vsB2",
             "E5vs6F","A1vs6F","C3vsD4","D4vs6F","B2vs6F","D4vsE5",
             "B2vsE5","B2vsD4")

#Separate Groups

### No-Reciprocity Group
g1<- data %>% select(Gender,Age,Empl.,Q17,B2vsC3,C3vsE5,A1vsE5,A1vsC3,
                   A1vsD4,C3vs6F,A1vsB2,E5vs6F,A1vs6F,C3vsD4,D4vs6F,
                   B2vs6F,D4vsE5,B2vsE5,B2vsD4) %>% 
        filter(B2vsC3!="")
colnames(g1)<-variables

### Reciprocity Group
g2<- data %>% select(Gender,Age,Empl.,Q17,B2vsC3.1,C3vsE5.1,A1vsE5.1,
                     A1vsC3.1,A1vsD4.1,C3vs6F.1,A1vsB2.1,E5vs6F.1,
                     A1vs6F.1,C3vsD4.1,D4vs6F.1,B2vs6F.1,
                     D4vsE5.1,B2vsE5.1,B2vsD4.1) %>% 
        filter(B2vsC3.1!="")
colnames(g2)<-variables


### No-Awareness Group
g3<- data %>% select(Gender,Age,Empl.,Q17,B2vsC3.2,C3vsE5.2,A1vsE5.2,
                     A1vsC3.2,A1vsD4.2,C3vs6F.2,A1vsB2.2,E5vs6F.2,
                     A1vs6F.2,C3vsD4.2,D4vs6F.2,B2vs6F.2,
                     D4vsE5.2,B2vsE5.2,B2vsD4.2) %>% 
        filter(B2vsC3.2!="")
colnames(g3)<-variables


#Building final data set
gr_data<- rbind(g1,g2,g3)
######gr_data[is.na(gr_data)] <- 0
tidy<-apply(gr_data, 2, as.numeric)

# Defining Length of each group
l1<- nrow(g1)
l2<- nrow(g2)
l3<- nrow(g3)

# Create vector defining each experimental condition
cond_length<-c(l1,l2,l3)
condition<- rep.int(c(1:3), times= cond_length)

# Joining data with groups information
clean<-cbind(tidy, condition)

# Create CSV File with clean data
write.csv(clean, file="clean_data_exp3.csv")

```

##Sample dataset
```{r, echo=TRUE}
head(clean)
```
