---
title: "Incentives_Core_Analysis"
author: "Juan Carpio"
date: "22 January 2016"
output: html_document
---


```{r,echo=TRUE, eval=TRUE, include=FALSE, cache=FALSE}
# Reading Clean File and setting relevant libraries.

## Change working directory
setwd("C:/Users/K56CA/Dropbox/PhD/Experiments Incentives/Follow_Up_Incentives")

##Relevant libraries
library("Hmisc")
library("dplyr")
library("tidyr")
library("ggplot2")
library("reshape2")
library("leaps")


## read raw_data
data_clean_imp<-read.csv("clean_data.csv")
## correcting ID veriable
data_clean<- mutate(data_clean_imp, ID= X+1) %>% 
        select(ID, everything(), -X)

##Define factor variables

data_clean$r_amount <- factor(data_clean$r_amount, levels = c(1,2),
                      labels = c("£5", "£2")) 

data_clean$r_type <- factor(data_clean$r_type, levels = c(1,2),
                    labels = c("Cash", "Product")) 

data_clean$gender <- factor(data_clean$gender, levels = c(1,2),
                    labels = c("Male", "Female"))

data_clean$income <- factor(data_clean$income, levels = c(1:5),
                    labels = c("< 15k", "15k-19k",
                               "20k-29k", "> 30k", "No.Ans")) 

data_clean$employ <- factor(data_clean$employ, levels = c(1:6),
                    labels = c("FT-Emp", "PT-Emp","Unempl.", 
                               "Stud.", "Retired","Other")) 


## Adding totals for Measures: Neg.Evaluations and Expectations 

expect_1<-c("exp_x1_K","exp_x1_T", "exp_x1_S.R","exp_x1_G")
expect_2<-c("exp_x2_K","exp_x2_T", "exp_x2_S.R","exp_x2_G")
expect_all<-c("exp_x1_K","exp_x1_T", "exp_x1_S.R","exp_x1_G",
              "exp_x2_K","exp_x2_T", "exp_x2_S.R","exp_x2_G")
neg_eval<-c("neg.ev_1","neg.ev_2.R","neg.ev_3","neg.ev_4.R",
            "neg.ev_5","neg.ev_6","neg.ev_7.R","neg.ev_8",
            "neg.ev_9","neg.ev_10.R", "neg.ev_11","neg.ev_12")

final_df<-data_clean %>% mutate(
        tot_exp1 = rowMeans(.[expect_1]),
        tot_exp2 = rowMeans(.[expect_2]),
        exp_all = rowMeans(.[expect_2]),
        tot_neg_eval = rowMeans(.[neg_eval])
        )  


# Code to audit cases ###################
# final_df %>% filter(ID==90) %>% gather()
#########################################

```


#1- ORDINAL LOGISTIG REGRESSION

### 1.1- Model Dep. Variable sharing with 2 friends
```{r, echo=FALSE, eval=TRUE, include=TRUE, cache=FALSE}
library("MASS")# Ordinal logistic regression

long_data<-melt(final_df, measure.var= c("vd_2f"),
        id.var = c("r_type", "r_amount", "tot_neg_eval", "tot_exp1",
                   "tot_exp2"))

long_data[[7]]=factor(long_data[[7]])

m1 <- polr(value ~ r_type+ r_amount+ tot_exp1+ tot_exp2,
           data = long_data, Hess=TRUE)
ctable <- coef(summary(m1))
p <- as.numeric(pnorm(abs(ctable[,"t value"]), lower.tail= FALSE) *2)
p<-round(p,3)
ctable <- cbind(ctable, "p value" = p)
ctable

```

### 1.2- Model Dep. Variable sharing with 1 friend
```{r, echo=FALSE, eval=TRUE, include=TRUE, cache=TRUE}

#library("MASS")# Ordinal logistic regression

long_data<-melt(final_df, measure.var= c("vd_1f"),
        id.var = c("r_type", "r_amount", "tot_neg_eval", "tot_exp1",
                   "tot_exp2"))

long_data[[7]]=factor(long_data[[7]])

m2 <- polr(factor(vd_1f) ~ r_type+ r_amount+ tot_exp1+ tot_exp2,
           data = final_df, Hess=TRUE)
ctable <- coef(summary(m2))
p <- as.numeric(pnorm(abs(ctable[,"t value"]), lower.tail= FALSE) *2)
p<-round(p,3)
ctable <- cbind(ctable, "p value" = p)
ctable

```

### 1.3- Model Dep. Variable not sharing 
```{r,echo=FALSE, eval=TRUE, include=TRUE, cache=TRUE}

#library("MASS")# Ordinal logistic regression

long_data<-melt(final_df, measure.var= c("vd_0f"),
        id.var = c("r_type", "r_amount", "tot_neg_eval", "tot_exp1",
                   "tot_exp2"))

long_data[[7]]=factor(long_data[[7]])

m3 <- polr(factor(vd_0f) ~ r_type+ r_amount+ tot_exp1+ tot_exp2,
           data = final_df, Hess=TRUE)
ctable <- coef(summary(m3))
p <- as.numeric(pnorm(abs(ctable[,"t value"]), lower.tail= FALSE) *2)
p<-round(p,3)
ctable <- cbind(ctable, "p value" = p)
ctable

```

#1- ORDINAL REGRESSION

```{r, echo=FALSE, eval=TRUE, include=TRUE, cache=FALSE}
library("ordinal")# Ordinal logistic regression

long_data<-melt(final_df, measure.var= c("vd_0f","vd_1f","vd_2f"),
        id.var = c("ID","r_type", "r_amount", "tot_neg_eval",
                   "tot_exp1","tot_exp2")) 

long_data[[8]]=factor(long_data[[8]])


mod <- clm(value ~ r_type+ r_amount + variable,
           data = long_data)

mod2 <- clm(value ~ r_type+ r_amount + variable + tot_neg_eval,
           data = long_data)

summary(mod)
summary(mod2)

```

